/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Test_py.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Test_py.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Python.geometry} material={materials.CubeMat} position={[2.1, 2.1, 2.1]} />
    </group>
  )
}

useGLTF.preload('/Test_py.glb')
