/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Core.glb
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

function HoverGroup({
  position,
  children,
  meshColors,
  colored,
  name,
  onHoverChange,
  groupRef,
  flashRef,
  visible = true,
}) {
  const [hover, setHover] = useState(false);
  const flashing = useRef(false);
  const matRefs = useRef(meshColors.map(() => null));
  const data = useRef({
    colors: meshColors.map(
      (_, i) => new THREE.Color(i === 0 ? "#ffffff" : "#000000"),
    ),
    targets: meshColors.map((c) => new THREE.Color(c)),
    colorT: 1,
  });

  // Expose a flash trigger to parent
  React.useEffect(() => {
    if (!flashRef) return;
    flashRef.current = () => {
      flashing.current = true;
      data.current.colorT = 0;
      gsap.to(data.current, {
        colorT: 1,
        duration: 0.4,
        ease: "power2.out",
        onComplete: () => {
          gsap.to(data.current, {
            colorT: 0,
            duration: 0.6,
            delay: 0.3,
            ease: "power2.in",
            onComplete: () => {
              flashing.current = false;
            },
          });
        },
      });
    };
  }, [flashRef]);

  useFrame((_, delta) => {
    const d = data.current;
    const colorTarget = flashing.current
      ? d.colorT
      : colored
        ? hover
          ? 1
          : 0
        : 1;
    if (!flashing.current)
      d.colorT = THREE.MathUtils.damp(d.colorT, colorTarget, 5, delta);

    matRefs.current.forEach((mat, i) => {
      if (mat) {
        if (i === 0) {
          mat.color.set("#ffffff");
        } else {
          d.colors[i].lerpColors(
            new THREE.Color("#000000"),
            d.targets[i],
            d.colorT,
          );
          mat.color.copy(d.colors[i]);
        }
      }
    });
  });

  return (
    <group
      ref={groupRef}
      position={position}
      visible={visible}
      onPointerOver={(e) => {
        if (colored) {
          e.stopPropagation();
          setHover(true);
          onHoverChange?.(name);
        }
      }}
      onPointerOut={(e) => {
        if (colored) {
          e.stopPropagation();
          setHover(false);
          onHoverChange?.(null);
        }
      }}
    >
      {React.Children.map(children, (child, i) =>
        React.cloneElement(child, {
          children: (
            <meshStandardMaterial
              ref={(el) => (matRefs.current[i] = el)}
              color={i === 0 ? "#ffffff" : "#000000"}
            />
          ),
        }),
      )}
    </group>
  );
}

export function Core({
  colored,
  onHoverChange,
  scrollTriggerRef,
  handoffScrollRef,
  onFlash,
  onHandoffStart,
  onHandoffComplete,
  onHandoffReset,
  coreGroupRef,
  logicGroupRef,
  ...props
}) {
  const { nodes } = useGLTF("/Core.glb");

  const localCoreGroupRef = useRef();
  const rootCoreGroupRef = coreGroupRef || localCoreGroupRef;

  const nodeRef = useRef();
  const postgresRef = useRef();
  const expressRef = useRef();
  const gitRef = useRef();
  const kubernetesRef = useRef();
  const electronRef = useRef();
  const dockerRef = useRef();
  const awsRef = useRef();

  const nodeFlash = useRef();
  const postgresFlash = useRef();
  const expressFlash = useRef();
  const gitFlash = useRef();

  const kubernetesFlash = useRef();
  const electronFlash = useRef();
  const dockerFlash = useRef();
  const awsFlash = useRef();

  // Unified animation: all 8 cubes in a single cohesive sequence
  useGSAP(
    () => {
      const trigger = scrollTriggerRef?.current;
      if (!trigger) return;

      // All entries in one sequence — each cube animates from its "from" direction
      const entries = [
        {
          ref: expressRef,
          flashRef: expressFlash,
          axis: "y",
          from: -10,
          name: "Express",
        },
        {
          ref: postgresRef,
          flashRef: postgresFlash,
          axis: "y",
          from: -10,
          name: "Postgres",
        },
        {
          ref: nodeRef,
          flashRef: nodeFlash,
          axis: "y",
          from: -10,
          name: "Node.js",
        },
        { ref: gitRef, flashRef: gitFlash, axis: "y", from: -10, name: "Git" },
        {
          ref: electronRef,
          flashRef: electronFlash,
          axis: "z",
          from: -5,
          name: "Electron",
        },
        {
          ref: kubernetesRef,
          flashRef: kubernetesFlash,
          axis: "x",
          from: 5,
          name: "Kubernetes",
        },
        {
          ref: dockerRef,
          flashRef: dockerFlash,
          axis: "z",
          from: 5,
          name: "Docker",
        },
        { ref: awsRef, flashRef: awsFlash, axis: "x", from: -5, name: "AWS" },
      ];

      // Make all animated groups visible but transparent
      entries.forEach(({ ref }) => {
        if (ref.current) {
          ref.current.visible = true;
          ref.current.traverse((child) => {
            if (child.material) {
              child.material.transparent = true;
              child.material.opacity = 0;
            }
          });
        }
      });

      // Single GSAP timeline scrubbed by scroll
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: trigger,
          start: "top top",
          end: "bottom bottom",
          scrub: true,
        },
      });

      // Evenly space all 8 cubes across the scroll
      // Each cube gets a slice of the timeline to animate in, then holds
      const totalDuration = 8; // arbitrary timeline units
      const cubeDuration = 0.8; // how long each cube takes to arrive
      const spacing = totalDuration / entries.length; // time between each cube start

      entries.forEach(({ ref, flashRef, axis, from, name }, i) => {
        if (!ref.current) return;
        const offset = i * spacing;

        // Capture the final position value before animating
        const finalVal = ref.current.position[axis];

        // Animate position
        tl.fromTo(
          ref.current.position,
          { [axis]: from },
          { [axis]: finalVal, ease: "none", duration: cubeDuration },
          offset,
        );

        // Animate opacity
        ref.current.traverse((child) => {
          if (child.material) {
            tl.fromTo(
              child.material,
              { opacity: 0 },
              { opacity: 1, ease: "none", duration: cubeDuration },
              offset,
            );
          }
        });

        // Fire flash when cube arrives at final position
        const fired = { value: false };
        ScrollTrigger.create({
          trigger: trigger,
          start: "top top",
          end: "bottom bottom",
          onUpdate: () => {
            const pos = ref.current?.position;
            if (!pos) return;
            const dist = Math.abs(pos[axis] - finalVal);
            if (!fired.value && dist < 0.1) {
              fired.value = true;
              flashRef.current?.();
              onFlash?.(name);
            }
            // Reset when scrolled back so it can fire again
            if (fired.value && dist > 0.5) {
              fired.value = false;
            }
          },
        });
      });
    },
    { dependencies: [scrollTriggerRef] },
  );

  // After Core section completes, move Core away on z while Logic comes forward — scrubbed by scroll.
  useGSAP(
    () => {
      const coreGroup = rootCoreGroupRef?.current;
      const handoffTrigger = handoffScrollRef?.current;
      if (!coreGroup || !handoffTrigger) return;

      gsap.set(coreGroup.position, { z: 0 });
      const liveLogicGroup = logicGroupRef?.current;
      if (liveLogicGroup) gsap.set(liveLogicGroup.position, { z: -2.1 });

      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: handoffTrigger,
          start: "top top",
          end: "bottom bottom",
          scrub: 1,
          onEnter: () => onHandoffStart?.(),
          onEnterBack: () => onHandoffStart?.(),
          onLeave: () => onHandoffComplete?.(),
          onLeaveBack: () => onHandoffReset?.(),
        },
      });

      tl.to(coreGroup.position, { z: 20, ease: "none" }, 0);

      if (liveLogicGroup) {
        tl.to(liveLogicGroup.position, { z: 0, ease: "none" }, 0);
      }
    },
    {
      dependencies: [
        handoffScrollRef,
        coreGroupRef,
        logicGroupRef,
        onHandoffStart,
        onHandoffComplete,
        onHandoffReset,
      ],
    },
  );

  return (
    <group
      ref={rootCoreGroupRef}
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      position={[0, 0, 0]}
    >
      <HoverGroup
        groupRef={nodeRef}
        flashRef={nodeFlash}
        position={[2.1, 0, 0]}
        meshColors={["#ffffff", "#5FA04E"]}
        colored={colored}
        name="Node.js"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.NodeJS_1.geometry} />
        <mesh geometry={nodes.NodeJS_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={postgresRef}
        flashRef={postgresFlash}
        position={[-2.1, 0, 0]}
        meshColors={["#ffffff", "#4169E1"]}
        colored={colored}
        name="Postgres"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Postgres_1.geometry} />
        <mesh geometry={nodes.Postgres_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={expressRef}
        flashRef={expressFlash}
        position={[0, 0, -2.1]}
        meshColors={["#ffffff", "#47848F"]}
        colored={colored}
        name="Express"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Express_1.geometry} />
        <mesh geometry={nodes.Express_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={kubernetesRef}
        flashRef={kubernetesFlash}
        position={[2.1, 0, -2.1]}
        meshColors={["#ffffff", "#326CE5"]}
        colored={colored}
        name="Kubernetes"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Kubernetes_1.geometry} />
        <mesh geometry={nodes.Kubernetes_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={electronRef}
        flashRef={electronFlash}
        position={[-2.1, 0, -2.1]}
        meshColors={["#ffffff", "#47848F"]}
        colored={colored}
        name="Electron"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Electron_1.geometry} />
        <mesh geometry={nodes.Electron_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={gitRef}
        flashRef={gitFlash}
        position={[0, 0, 2.1]}
        meshColors={["#ffffff", "#F05032"]}
        colored={colored}
        name="Git"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Git_1.geometry} />
        <mesh geometry={nodes.Git_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={dockerRef}
        flashRef={dockerFlash}
        position={[2.1, 0, 2.1]}
        meshColors={["#ffffff", "#2496ED"]}
        colored={colored}
        name="Docker"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Docker_1.geometry} />
        <mesh geometry={nodes.Docker_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={awsRef}
        flashRef={awsFlash}
        position={[-2.1, 0, 2.1]}
        meshColors={["#ffffff", "#000000", "#E77B0D"]}
        colored={colored}
        name="AWS"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.AWS_1.geometry} />
        <mesh geometry={nodes.AWS_2.geometry} />
        <mesh geometry={nodes.AWS_3.geometry} />
      </HoverGroup>
      <HoverGroup
        position={[0, 0, 0]}
        meshColors={["#ffffff", "#111111"]}
        colored={colored}
        name="Next.js"
        onHoverChange={onHoverChange}
      >
        <mesh geometry={nodes.Next_1.geometry} />
        <mesh geometry={nodes.Next_2.geometry} />
      </HoverGroup>
    </group>
  );
}

useGLTF.preload("/Core.glb");
