/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, animations } = useGLTF('/Cubes.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* Shell layer — y=4.2 */}
        <group name="React" position={[0, 4.2, 0]}>
          <mesh name="React_1" castShadow receiveShadow geometry={nodes.React_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="React_2" castShadow receiveShadow geometry={nodes.React_2.geometry}>
            <meshStandardMaterial color="#61DAFB" />
          </mesh>
        </group>
        <group name="Blender(Rig)" position={[2.1, 4.2, 0]}>
          <mesh name="Rig" castShadow receiveShadow geometry={nodes.Rig.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Rig_1" castShadow receiveShadow geometry={nodes.Rig_1.geometry}>
            <meshStandardMaterial color="#E77503" />
          </mesh>
          <mesh name="Rig_2" castShadow receiveShadow geometry={nodes.Rig_2.geometry}>
            <meshStandardMaterial color="#0E4FE7" />
          </mesh>
          <mesh name="Rig_3" castShadow receiveShadow geometry={nodes.Rig_3.geometry}>
            <meshStandardMaterial color="#656565" />
          </mesh>
        </group>
        <group name="Tailwind" position={[-2.1, 4.2, 0]}>
          <mesh name="Tailwind_1" castShadow receiveShadow geometry={nodes.Tailwind_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Tailwind_2" castShadow receiveShadow geometry={nodes.Tailwind_2.geometry}>
            <meshStandardMaterial color="#06B6D4" />
          </mesh>
        </group>
        <group name="CSS" position={[0, 4.2, -2.1]}>
          <mesh name="CSS_1" castShadow receiveShadow geometry={nodes.CSS_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="CSS_2" castShadow receiveShadow geometry={nodes.CSS_2.geometry}>
            <meshStandardMaterial color="#663399" />
          </mesh>
        </group>
        <group name="JS" position={[2.1, 4.2, -2.1]}>
          <mesh name="JS_1" castShadow receiveShadow geometry={nodes.JS_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="JS_2" castShadow receiveShadow geometry={nodes.JS_2.geometry}>
            <meshStandardMaterial color="#F7DF1E" />
          </mesh>
        </group>
        <group name="HTML" position={[-2.1, 4.2, -2.1]}>
          <mesh name="Html" castShadow receiveShadow geometry={nodes.Html.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Html_1" castShadow receiveShadow geometry={nodes.Html_1.geometry}>
            <meshStandardMaterial color="#E34F26" />
          </mesh>
        </group>
        <group name="Typescript" position={[0, 4.2, 2.1]}>
          <mesh name="Typescript_1" castShadow receiveShadow geometry={nodes.Typescript_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Typescript_2" castShadow receiveShadow geometry={nodes.Typescript_2.geometry}>
            <meshStandardMaterial color="#3178C6" />
          </mesh>
        </group>
        <group name="ThreeJS" position={[2.1, 4.2, 2.1]}>
          <mesh name="ThreeJS_1" castShadow receiveShadow geometry={nodes.ThreeJS_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="ThreeJS_2" castShadow receiveShadow geometry={nodes.ThreeJS_2.geometry}>
            <meshStandardMaterial color="#000000" />
          </mesh>
        </group>
        <group name="GSAP" position={[-2.1, 4.2, 2.1]}>
          <mesh name="Gsap" castShadow receiveShadow geometry={nodes.Gsap.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Gsap_1" castShadow receiveShadow geometry={nodes.Gsap_1.geometry}>
            <meshStandardMaterial color="#0AE448" />
          </mesh>
        </group>

        {/* Core layer — y=0 */}
        <group name="Next">
          <mesh name="Next_1" castShadow receiveShadow geometry={nodes.Next_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Next_2" castShadow receiveShadow geometry={nodes.Next_2.geometry}>
            <meshStandardMaterial color="#111111" />
          </mesh>
        </group>
        <group name="NodeJS" position={[2.1, 0, 0]}>
          <mesh name="NodeJS_1" castShadow receiveShadow geometry={nodes.NodeJS_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="NodeJS_2" castShadow receiveShadow geometry={nodes.NodeJS_2.geometry}>
            <meshStandardMaterial color="#5FA04E" />
          </mesh>
        </group>
        <group name="Postgres" position={[-2.1, 0, 0]}>
          <mesh name="Postgres_1" castShadow receiveShadow geometry={nodes.Postgres_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Postgres_2" castShadow receiveShadow geometry={nodes.Postgres_2.geometry}>
            <meshStandardMaterial color="#4169E1" />
          </mesh>
        </group>
        <group name="Express" position={[0, 0, -2.1]}>
          <mesh name="Express_1" castShadow receiveShadow geometry={nodes.Express_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Express_2" castShadow receiveShadow geometry={nodes.Express_2.geometry}>
            <meshStandardMaterial color="#47848F" />
          </mesh>
        </group>
        <group name="Kubernetes" position={[2.1, 0, -2.1]}>
          <mesh name="Kubernetes_1" castShadow receiveShadow geometry={nodes.Kubernetes_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Kubernetes_2" castShadow receiveShadow geometry={nodes.Kubernetes_2.geometry}>
            <meshStandardMaterial color="#326CE5" />
          </mesh>
        </group>
        <group name="Electron" position={[-2.1, 0, -2.1]}>
          <mesh name="Electron_1" castShadow receiveShadow geometry={nodes.Electron_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Electron_2" castShadow receiveShadow geometry={nodes.Electron_2.geometry}>
            <meshStandardMaterial color="#47848F" />
          </mesh>
        </group>
        <group name="Git" position={[0, 0, 2.1]}>
          <mesh name="Git_1" castShadow receiveShadow geometry={nodes.Git_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Git_2" castShadow receiveShadow geometry={nodes.Git_2.geometry}>
            <meshStandardMaterial color="#F05032" />
          </mesh>
        </group>
        <group name="Docker" position={[2.1, 0, 2.1]}>
          <mesh name="Docker_1" castShadow receiveShadow geometry={nodes.Docker_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Docker_2" castShadow receiveShadow geometry={nodes.Docker_2.geometry}>
            <meshStandardMaterial color="#2496ED" />
          </mesh>
        </group>
        <group name="AWS" position={[-2.1, 0, 2.1]}>
          <mesh name="AWS_1" castShadow receiveShadow geometry={nodes.AWS_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="AWS_2" castShadow receiveShadow geometry={nodes.AWS_2.geometry}>
            <meshStandardMaterial color="#000000" />
          </mesh>
          <mesh name="AWS_3" castShadow receiveShadow geometry={nodes.AWS_3.geometry}>
            <meshStandardMaterial color="#E77B0D" />
          </mesh>
        </group>

        {/* Logic layer — y=2.1 */}
        <group name="Blender(Geo)" position={[0, 2.1, 0]}>
          <mesh name="Geo" castShadow receiveShadow geometry={nodes.Geo.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Geo_1" castShadow receiveShadow geometry={nodes.Geo_1.geometry}>
            <meshStandardMaterial color="#E77503" />
          </mesh>
          <mesh name="Geo_2" castShadow receiveShadow geometry={nodes.Geo_2.geometry}>
            <meshStandardMaterial color="#0E4FE7" />
          </mesh>
          <mesh name="Geo_3" castShadow receiveShadow geometry={nodes.Geo_3.geometry}>
            <meshStandardMaterial color="#656565" />
          </mesh>
        </group>
        <group name="SubstancePainter" position={[2.1, 2.1, 0]}>
          <mesh name="SubstancePainter_1" castShadow receiveShadow geometry={nodes.SubstancePainter_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="SubstancePainter_2" castShadow receiveShadow geometry={nodes.SubstancePainter_2.geometry}>
            <meshStandardMaterial color="#E70013" />
          </mesh>
        </group>
        <group name="Webgl" position={[-2.1, 2.1, 0]}>
          <mesh name="WebGL" castShadow receiveShadow geometry={nodes.WebGL.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="WebGL_1" castShadow receiveShadow geometry={nodes.WebGL_1.geometry}>
            <meshStandardMaterial color="#990000" />
          </mesh>
        </group>
        <group name="Blender(Modelling)" position={[0, 2.1, -2.1]}>
          <mesh name="Modelling" castShadow receiveShadow geometry={nodes.Modelling.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Modelling_1" castShadow receiveShadow geometry={nodes.Modelling_1.geometry}>
            <meshStandardMaterial color="#E77503" />
          </mesh>
          <mesh name="Modelling_2" castShadow receiveShadow geometry={nodes.Modelling_2.geometry}>
            <meshStandardMaterial color="#0E4FE7" />
          </mesh>
          <mesh name="Modelling_3" castShadow receiveShadow geometry={nodes.Modelling_3.geometry}>
            <meshStandardMaterial color="#656565" />
          </mesh>
        </group>
        <group name="Pytorch" position={[2.1, 2.1, -2.1]}>
          <mesh name="Pytorch_1" castShadow receiveShadow geometry={nodes.Pytorch_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Pytorch_2" castShadow receiveShadow geometry={nodes.Pytorch_2.geometry}>
            <meshStandardMaterial color="#EE4C2C" />
          </mesh>
        </group>
        <group name="Unity" position={[-2.1, 2.1, -2.1]}>
          <mesh name="Unity_1" castShadow receiveShadow geometry={nodes.Unity_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Unity_2" castShadow receiveShadow geometry={nodes.Unity_2.geometry}>
            <meshStandardMaterial color="#aaaaaa" />
          </mesh>
        </group>
        <group name="Comfy" position={[0, 2.1, 2.1]}>
          <mesh name="ComfyUI" castShadow receiveShadow geometry={nodes.ComfyUI.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="ComfyUI_1" castShadow receiveShadow geometry={nodes.ComfyUI_1.geometry}>
            <meshStandardMaterial color="#E7DA00" />
          </mesh>
        </group>
        <group name="Python" position={[2.1, 2.1, 2.1]}>
          <mesh name="Python_1" castShadow receiveShadow geometry={nodes.Python_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="Python_2" castShadow receiveShadow geometry={nodes.Python_2.geometry}>
            <meshStandardMaterial color="#3776AB" />
          </mesh>
          <mesh name="Python_3" castShadow receiveShadow geometry={nodes.Python_3.geometry}>
            <meshStandardMaterial color="#E7B628" />
          </mesh>
        </group>
        <group name="HuggingFace" position={[-2.1, 2.1, 2.1]}>
          <mesh name="HuggingFace_1" castShadow receiveShadow geometry={nodes.HuggingFace_1.geometry}>
            <meshStandardMaterial color="#ffffff" />
          </mesh>
          <mesh name="HuggingFace_2" castShadow receiveShadow geometry={nodes.HuggingFace_2.geometry}>
            <meshStandardMaterial color="#FFD21E" />
          </mesh>
          <mesh name="HuggingFace_3" castShadow receiveShadow geometry={nodes.HuggingFace_3.geometry}>
            <meshStandardMaterial color="#000000" />
          </mesh>
          <mesh name="HuggingFace_4" castShadow receiveShadow geometry={nodes.HuggingFace_4.geometry}>
            <meshStandardMaterial color="#E77336" />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cubes.glb')
