/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Navigation_Cube.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Navigation_Cube.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} position={[0, -0.171, 0]} scale={0.413} />
    </group>
  )
}

useGLTF.preload('/Navigation_Cube.glb')
