/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Logic.glb
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

function HoverGroup({
  position,
  children,
  meshColors,
  hideIndices = [],
  colored,
  name,
  onHoverChange,
  groupRef,
  flashRef,
  visible = true,
}) {
  const [hover, setHover] = useState(false);
  const flashing = useRef(false);
  const matRefs = useRef(meshColors.map(() => null));
  const data = useRef({
    colors: meshColors.map(
      (_, i) => new THREE.Color(i === 0 ? "#ffffff" : "#000000"),
    ),
    targets: meshColors.map((c) => new THREE.Color(c)),
    colorT: 1,
  });

  // Expose a flash trigger to parent
  React.useEffect(() => {
    if (!flashRef) return;
    flashRef.current = () => {
      flashing.current = true;
      data.current.colorT = 0;
      gsap.to(data.current, {
        colorT: 1,
        duration: 0.4,
        ease: "power2.out",
        onComplete: () => {
          gsap.to(data.current, {
            colorT: 0,
            duration: 0.6,
            delay: 0.3,
            ease: "power2.in",
            onComplete: () => {
              flashing.current = false;
            },
          });
        },
      });
    };
  }, [flashRef]);

  useFrame((_, delta) => {
    const d = data.current;
    const colorTarget = flashing.current
      ? d.colorT
      : colored
        ? hover
          ? 1
          : 0
        : 1;
    if (!flashing.current)
      d.colorT = THREE.MathUtils.damp(d.colorT, colorTarget, 5, delta);

    matRefs.current.forEach((mat, i) => {
      if (mat) {
        if (i === 0) {
          mat.color.set("#ffffff");
        } else {
          if (hideIndices.includes(i)) mat.visible = colored ? hover : true;
          d.colors[i].lerpColors(
            new THREE.Color("#000000"),
            d.targets[i],
            d.colorT,
          );
          mat.color.copy(d.colors[i]);
        }
      }
    });
  });

  return (
    <group
      ref={groupRef}
      position={position}
      visible={visible}
      onPointerOver={(e) => {
        if (colored) {
          e.stopPropagation();
          setHover(true);
          onHoverChange?.(name);
        }
      }}
      onPointerOut={(e) => {
        if (colored) {
          e.stopPropagation();
          setHover(false);
          onHoverChange?.(null);
        }
      }}
    >
      {React.Children.map(children, (child, i) =>
        React.cloneElement(child, {
          children: (
            <meshStandardMaterial
              ref={(el) => (matRefs.current[i] = el)}
              color={i === 0 ? "#ffffff" : "#000000"}
            />
          ),
        }),
      )}
    </group>
  );
}

export function Logic({
  colored,
  onHoverChange,
  scrollTriggerRef,
  onFlash,
  logicGroupRef,
  ...props
}) {
  const { nodes } = useGLTF("/Logic.glb");

  const localLogicGroupRef = useRef();
  const rootGroupRef = logicGroupRef || localLogicGroupRef;

  const substanceRef = useRef();
  const webglRef = useRef();
  const modellingRef = useRef();
  const pytorchRef = useRef();
  const unityRef = useRef();
  const comfyRef = useRef();
  const pythonRef = useRef();
  const huggingRef = useRef();
  const blenderRef = useRef();

  const substanceFlash = useRef();
  const webglFlash = useRef();
  const modellingFlash = useRef();
  const pytorchFlash = useRef();
  const unityFlash = useRef();
  const comfyFlash = useRef();
  const pythonFlash = useRef();
  const huggingFlash = useRef();

  // Logic section sequence: reveal Blender first, then animate remaining cubes.
  useGSAP(
    () => {
      const trigger = scrollTriggerRef?.current;
      if (!trigger) return;

      const entries = [
        {
          ref: substanceRef,
          flashRef: substanceFlash,
          axis: "y",
          from: 10,
          name: "Substance Painter",
        },
        {
          ref: webglRef,
          flashRef: webglFlash,
          axis: "y",
          from: 10,
          name: "WebGL",
        },
        {
          ref: modellingRef,
          flashRef: modellingFlash,
          axis: "y",
          from: 10,
          name: "Modelling",
        },
        {
          ref: comfyRef,
          flashRef: comfyFlash,
          axis: "y",
          from: 10,
          name: "ComfyUI",
        },
        {
          ref: pytorchRef,
          flashRef: pytorchFlash,
          axis: "z",
          from: -5,
          name: "Pytorch",
        },
        {
          ref: unityRef,
          flashRef: unityFlash,
          axis: "x",
          from: -5,
          name: "Unity",
        },
        {
          ref: pythonRef,
          flashRef: pythonFlash,
          axis: "x",
          from: 5,
          name: "Python",
        },
        {
          ref: huggingRef,
          flashRef: huggingFlash,
          axis: "z",
          from: 5,
          name: "HuggingFace",
        },
      ];

      const groups = [blenderRef, ...entries.map(({ ref }) => ref)];

      // Start with every Logic cube hidden and transparent.
      groups.forEach((ref) => {
        if (ref.current) {
          ref.current.visible = false;
          ref.current.traverse((child) => {
            if (child.material) {
              child.material.transparent = true;
              child.material.opacity = 0;
            }
          });
        }
      });

      // Single GSAP timeline scrubbed by scroll
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: trigger,
          start: "top top",
          end: "bottom bottom",
          scrub: true,
        },
      });

      const totalDuration = 9;
      const blenderFadeDuration = 0.6;
      const blenderStart = 0;
      const cubesStart = blenderStart + blenderFadeDuration + 0.2;
      const cubeDuration = 0.8;
      // Reserve one cubeDuration for the last cube so it fully arrives at timeline end.
      const spacing =
        entries.length > 1
          ? (totalDuration - cubesStart - cubeDuration) / (entries.length - 1)
          : 0;

      // Blender: fade in via opacity (scrubs both ways)
      if (blenderRef.current) {
        blenderRef.current.visible = true;
        blenderRef.current.traverse((child) => {
          if (child.material) {
            tl.fromTo(
              child.material,
              { opacity: 0 },
              { opacity: 1, ease: "none", duration: blenderFadeDuration },
              blenderStart,
            );
          }
        });
      }

      const blenderFired = { value: false };
      ScrollTrigger.create({
        trigger: trigger,
        start: "top top",
        end: "bottom bottom",
        onUpdate: (self) => {
          // Derive visibility from scroll progress for Blender
          if (blenderRef.current) {
            blenderRef.current.visible = self.progress > 0;
          }
          if (!blenderFired.value && self.progress > 0.27) {
            blenderFired.value = true;
            onFlash?.("Blender");
          }
          if (blenderFired.value && self.progress < 0.2) {
            blenderFired.value = false;
          }
        },
      });

      entries.forEach(({ ref, flashRef, axis, from, name }, i) => {
        if (!ref.current) return;
        const offset = cubesStart + i * spacing;

        // Keep visible=true so opacity controls appearance; scrub handles both directions
        ref.current.visible = true;

        const finalVal = ref.current.position[axis];

        tl.fromTo(
          ref.current.position,
          { [axis]: from },
          { [axis]: finalVal, ease: "none", duration: cubeDuration },
          offset,
        );

        ref.current.traverse((child) => {
          if (child.material) {
            tl.fromTo(
              child.material,
              { opacity: 0 },
              { opacity: 1, ease: "none", duration: cubeDuration },
              offset,
            );
          }
        });

        const fired = { value: false };
        ScrollTrigger.create({
          trigger: trigger,
          start: "top top",
          end: "bottom bottom",
          onUpdate: () => {
            const pos = ref.current?.position;
            if (!pos) return;
            const dist = Math.abs(pos[axis] - finalVal);
            if (!fired.value && dist < 0.1) {
              fired.value = true;
              flashRef.current?.();
              onFlash?.(name);
            }
            if (fired.value && dist > 0.5) {
              fired.value = false;
            }
          },
        });
      });
    },
    { dependencies: [scrollTriggerRef] },
  );

  return (
    <group
      ref={rootGroupRef}
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <HoverGroup
        groupRef={substanceRef}
        flashRef={substanceFlash}
        position={[2.1, 2.1, 0]}
        meshColors={["#ffffff", "#E70013"]}
        colored={colored}
        name="Substance Painter"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.SubstancePainter_1.geometry} />
        <mesh geometry={nodes.SubstancePainter_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={webglRef}
        flashRef={webglFlash}
        position={[-2.1, 2.1, 0]}
        meshColors={["#ffffff", "#990000"]}
        colored={colored}
        name="WebGL"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.WebGL.geometry} />
        <mesh geometry={nodes.WebGL_1.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={modellingRef}
        flashRef={modellingFlash}
        position={[0, 2.1, -2.1]}
        meshColors={["#ffffff", "#E77503", "#0E4FE7", "#656565"]}
        colored={colored}
        name="Modelling"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Modelling.geometry} />
        <mesh geometry={nodes.Modelling_1.geometry} />
        <mesh geometry={nodes.Modelling_2.geometry} />
        <mesh geometry={nodes.Modelling_3.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={pytorchRef}
        flashRef={pytorchFlash}
        position={[2.1, 2.1, -2.1]}
        meshColors={["#ffffff", "#EE4C2C"]}
        colored={colored}
        name="Pytorch"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Pytorch_1.geometry} />
        <mesh geometry={nodes.Pytorch_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={unityRef}
        flashRef={unityFlash}
        position={[-2.1, 2.1, -2.1]}
        meshColors={["#ffffff", "#aaaaaa"]}
        colored={colored}
        name="Unity"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Unity_1.geometry} />
        <mesh geometry={nodes.Unity_2.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={comfyRef}
        flashRef={comfyFlash}
        position={[0, 2.1, 2.1]}
        meshColors={["#ffffff", "#E7DA00"]}
        colored={colored}
        name="ComfyUI"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.ComfyUI.geometry} />
        <mesh geometry={nodes.ComfyUI_1.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={pythonRef}
        flashRef={pythonFlash}
        position={[2.1, 2.1, 2.1]}
        meshColors={["#ffffff", "#3776AB", "#E7B628"]}
        colored={colored}
        name="Python"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Python_1.geometry} />
        <mesh geometry={nodes.Python_2.geometry} />
        <mesh geometry={nodes.Python_3.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={huggingRef}
        flashRef={huggingFlash}
        position={[-2.1, 2.1, 2.1]}
        meshColors={["#ffffff", "#FFD21E", "#000000", "#E77336"]}
        hideIndices={[2, 3]}
        colored={colored}
        name="HuggingFace"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.HuggingFace_1.geometry} />
        <mesh geometry={nodes.HuggingFace_2.geometry} />
        <mesh geometry={nodes.HuggingFace_3.geometry} />
        <mesh geometry={nodes.HuggingFace_4.geometry} />
      </HoverGroup>
      <HoverGroup
        groupRef={blenderRef}
        position={[0, 2.1, 0]}
        meshColors={["#ffffff", "#E77503", "#0E4FE7", "#656565"]}
        colored={colored}
        name="Blender"
        onHoverChange={onHoverChange}
        visible={false}
      >
        <mesh geometry={nodes.Geo.geometry} />
        <mesh geometry={nodes.Geo_1.geometry} />
        <mesh geometry={nodes.Geo_2.geometry} />
        <mesh geometry={nodes.Geo_3.geometry} />
      </HoverGroup>
    </group>
  );
}

useGLTF.preload("/Logic.glb");
