/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Shell.glb
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'


function HoverGroup({ position, children, meshColors, colored }) {
  const [hover, setHover] = useState(false)
  const matRefs = useRef(meshColors.map(() => null))
  const data = useRef({
    colors: meshColors.map((_, i) => new THREE.Color(i === 0 ? '#ffffff' : '#000000')),
    targets: meshColors.map(c => new THREE.Color(c)),
    colorT: 1,
  })

  useFrame((_, delta) => {
    const d = data.current
    const colorTarget = colored ? (hover ? 1 : 0) : 1
    d.colorT = THREE.MathUtils.damp(d.colorT, colorTarget, 5, delta)

    matRefs.current.forEach((mat, i) => {
      if (mat) {
        if (i === 0) {
          mat.color.set('#ffffff')
        } else {
          d.colors[i].lerpColors(new THREE.Color('#000000'), d.targets[i], d.colorT)
          mat.color.copy(d.colors[i])
        }
      }
    })
  })

  return (
    <group
      position={position}
      onPointerOver={() => colored && setHover(true)}
      onPointerOut={() => colored && setHover(false)}
    >
      {React.Children.map(children, (child, i) =>
        React.cloneElement(child, {
          children: (
            <meshStandardMaterial
              ref={el => (matRefs.current[i] = el)}
              color={i === 0 ? '#ffffff' : '#000000'}
            />
          ),
        })
      )}
    </group>
  )
}

export function Shell({ colored, ...props }) {
  const { nodes } = useGLTF('/Shell.glb')
  return (
    <group {...props} dispose={null}>
      <HoverGroup position={[0, 4.2, 0]} meshColors={['#ffffff', '#61DAFB']} colored={colored}>
        <mesh geometry={nodes.React_1.geometry} />
        <mesh geometry={nodes.React_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[2.1, 4.2, 0]} meshColors={['#ffffff', '#E77503', '#0E4FE7', '#656565']} colored={colored}>
        <mesh geometry={nodes.Rig.geometry} />
        <mesh geometry={nodes.Rig_1.geometry} />
        <mesh geometry={nodes.Rig_2.geometry} />
        <mesh geometry={nodes.Rig_3.geometry} />
      </HoverGroup>
      <HoverGroup position={[-2.1, 4.2, 0]} meshColors={['#ffffff', '#06B6D4']} colored={colored}>
        <mesh geometry={nodes.Tailwind_1.geometry} />
        <mesh geometry={nodes.Tailwind_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[0, 4.2, -2.1]} meshColors={['#ffffff', '#663399']} colored={colored}>
        <mesh geometry={nodes.CSS_1.geometry} />
        <mesh geometry={nodes.CSS_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[2.1, 4.2, -2.1]} meshColors={['#ffffff', '#F7DF1E']} colored={colored}>
        <mesh geometry={nodes.JS_1.geometry} />
        <mesh geometry={nodes.JS_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[-2.1, 4.2, -2.1]} meshColors={['#ffffff', '#E34F26']} colored={colored}>
        <mesh geometry={nodes.Html.geometry} />
        <mesh geometry={nodes.Html_1.geometry} />
      </HoverGroup>
      <HoverGroup position={[0, 4.2, 2.1]} meshColors={['#ffffff', '#3178C6']} colored={colored}>
        <mesh geometry={nodes.Typescript_1.geometry} />
        <mesh geometry={nodes.Typescript_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[2.1, 4.2, 2.1]} meshColors={['#ffffff', '#000000']} colored={colored}>
        <mesh geometry={nodes.ThreeJS_1.geometry} />
        <mesh geometry={nodes.ThreeJS_2.geometry} />
      </HoverGroup>
      <HoverGroup position={[-2.1, 4.2, 2.1]} meshColors={['#ffffff', '#0AE448']} colored={colored}>
        <mesh geometry={nodes.Gsap.geometry} />
        <mesh geometry={nodes.Gsap_1.geometry} />
      </HoverGroup>
    </group>
  )
}

useGLTF.preload('/Shell.glb')
